import Image from "next/image";
import { ButtonLink } from "@/components/button-link";
import { PageHero } from "@/components/page-hero";
import { MapIcon } from "@/components/icons";
import { business } from "@/data/business";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("About", "Learn about El Toro Loco, a Mexican restaurant in Whittier serving traditional dishes, handmade tortillas, and food for special gatherings.", "/about");

export default function AboutPage() { return <><PageHero eyebrow="About us" title="Traditional Mexican Food in Whittier" description="El Toro Loco serves a wide selection of traditional dishes at our Telegraph Road location." image="/images/traditional-dishes-signage.png" imageAlt="Traditional dishes pictured outside El Toro Loco" /><section className="section"><div className="container content-grid"><div className="prose"><p className="eyebrow">El Toro Loco</p><h2>Good Food, Close to Home</h2><p>El Toro Loco serves traditional Mexican dishes in Whittier, including carnitas, birria de chivo, barbacoa, menudo, pozole, tamales, chile relleno, and handmade tortillas.</p><p>Visit us at {business.address.singleLine}, or call ahead to ask about menu availability.</p><ButtonLink href={business.directionsUrl} external><MapIcon className="icon" /> Get Directions</ButtonLink></div><div className="content-image"><Image src="/images/storefront.png" alt="El Toro Loco restaurant storefront on Telegraph Road" fill sizes="(max-width:760px) 100vw, 45vw" /></div></div></section><section className="section cream"><div className="container"><div className="section-heading"><div><p className="eyebrow">What you’ll find</p><h2>A Menu Rooted in Tradition</h2></div></div><div className="values-grid"><article className="value-card"><h3>Traditional Dishes</h3><p>Carnitas, barbacoa, birria, menudo, pozole, tamales, and more.</p></article><article className="value-card"><h3>Handmade Tortillas</h3><p>Tortillas hechas a mano are proudly featured on the restaurant menu.</p></article><article className="value-card"><h3>Food for Parties</h3><p>Ask about select dishes and trays for special gatherings.</p></article></div></div></section></>; }
